name: foodtrucks
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.16.1
  sqflite: ^1.3.1
  flushbar: ^1.10.4
  flutter_svg: ^0.19.0
  path_provider: ^1.6.11
  image_picker: ^0.6.7+11
  map_launcher: ^0.12.2
  google_maps_flutter: ^0.5.33
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - assets/

  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-SemiBold.ttf
        - asset: fonts/Nunito-Regular.ttf
        - asset: fonts/Nunito-Medium.ttf
        - asset: fonts/Nunito-Light.ttf
        - asset: fonts/Nunito-ExtraLight.ttf 
        - asset: fonts/Nunito-ExtraBold.ttf
        - asset: fonts/Nunito-Bold.ttf
        - asset: fonts/Nunito-Black.ttf
          style: italic